name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Get npm latest version
        id: npm_latest
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          NPM_LATEST=$(npm view "$PACKAGE_NAME" version --registry https://registry.npmjs.org 2>/dev/null || echo "0.0.0")
          echo "npm latest version: $NPM_LATEST"
          echo "npm_latest=$NPM_LATEST" >> $GITHUB_OUTPUT

      - name: Determine release version
        id: version
        run: |
          # èŽ·å–å½“å‰ç‰ˆæœ¬
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NPM_LATEST="${{ steps.npm_latest.outputs.npm_latest }}"
          echo "Current version: $CURRENT_VERSION"
          echo "npm latest: $NPM_LATEST"

          # ç§»é™¤ beta åŽç¼€èŽ·å–åŸºç¡€ç‰ˆæœ¬
          BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-beta.*//')
          echo "Base version: $BASE_VERSION"

          # æ£€æŸ¥æ˜¯å¦æ˜¯ beta ç‰ˆæœ¬è½¬æ­£å¼ç‰ˆ
          if [[ "$CURRENT_VERSION" == *"-beta."* ]]; then
            # beta ç‰ˆæœ¬ï¼šç›´æŽ¥ä½¿ç”¨åŸºç¡€ç‰ˆæœ¬ä½œä¸ºæ­£å¼ç‰ˆ
            NEW_VERSION="$BASE_VERSION"
            echo "Converting beta to release: $CURRENT_VERSION -> $NEW_VERSION"
          else
            # éž beta ç‰ˆæœ¬ï¼šåŸºäºŽ npm æœ€æ–°ç‰ˆæœ¬é€’å¢ž patch
            MAJOR=$(echo "$NPM_LATEST" | cut -d. -f1)
            MINOR=$(echo "$NPM_LATEST" | cut -d. -f2)
            PATCH=$(echo "$NPM_LATEST" | cut -d. -f3)
            NEXT_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}"
            echo "Non-beta release: incrementing patch $NPM_LATEST -> $NEW_VERSION"
          fi

          # ç¡®ä¿æ–°ç‰ˆæœ¬å¤§äºŽ npm æœ€æ–°ç‰ˆæœ¬
          if [ -n "$NPM_LATEST" ] && [ "$NPM_LATEST" != "0.0.0" ]; then
            COMPARE_RESULT=$(printf "%s\n%s" "$NEW_VERSION" "$NPM_LATEST" | sort -V | tail -1)
            if [ "$COMPARE_RESULT" = "$NPM_LATEST" ] && [ "$NEW_VERSION" != "$NPM_LATEST" ]; then
              echo "::error::New version $NEW_VERSION is not greater than npm latest $NPM_LATEST"
              exit 1
            fi
          fi

          echo "New release version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # è®¡ç®—ä¸‹ä¸€ä¸ªå¼€å‘ç‰ˆæœ¬ (patch + 1, beta.0)
          MAJOR=$(echo "$NEW_VERSION" | cut -d. -f1)
          MINOR=$(echo "$NEW_VERSION" | cut -d. -f2)
          PATCH=$(echo "$NEW_VERSION" | cut -d. -f3)
          NEXT_PATCH=$((PATCH + 1))
          NEXT_DEV_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}-beta.0"
          echo "Next dev version: $NEXT_DEV_VERSION"
          echo "next_dev_version=$NEXT_DEV_VERSION" >> $GITHUB_OUTPUT

          # æ›´æ–° package.json ä¸ºæ­£å¼ç‰ˆæœ¬
          npm version "$NEW_VERSION" --no-git-tag-version

      - name: Make scripts executable
        run: chmod +x scripts/*.sh || true

      - name: Check for private links
        run: |
          echo "æ£€æŸ¥ npm å‘å¸ƒæ–‡ä»¶ä¸­æ˜¯å¦åŒ…å«ç§æœ‰é“¾æŽ¥..."
          ./scripts/check-private-links.sh

      - name: Update CHANGELOG
        run: |
          NEW_VERSION="${{ steps.version.outputs.version }}"
          echo "æ­£åœ¨æ›´æ–° CHANGELOG..."
          if [ -f scripts/update-changelog.sh ]; then
            ./scripts/update-changelog.sh "$NEW_VERSION"
          else
            echo "update-changelog.sh ä¸å­˜åœ¨ï¼Œè·³è¿‡"
          fi

      - name: Update README version and tool count
        run: |
          NEW_VERSION="${{ steps.version.outputs.version }}"

          # æ›´æ–°ç‰ˆæœ¬å·
          sed -i "s/\*\*å½“å‰ç‰ˆæœ¬\*\*: v[0-9.]*/**å½“å‰ç‰ˆæœ¬**: v${NEW_VERSION}/" README.md || true

          # æ›´æ–°å·¥å…·æ•°é‡
          if [ -f scripts/count-tools.sh ]; then
            ./scripts/count-tools.sh --update
          fi

      - name: Publish to npm
        run: npm publish --tag latest --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit, tag and push to main
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          git add package.json README.md CHANGELOG.md
          git commit -m "chore: release v${VERSION} [skip ci]" || true
          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin main --tags

      - name: Sync version to dev branch
        run: |
          NEXT_DEV_VERSION="${{ steps.version.outputs.next_dev_version }}"
          RELEASE_VERSION="${{ steps.version.outputs.version }}"

          echo "Syncing to dev branch..."
          git fetch origin dev
          git checkout dev
          git pull origin dev

          # æ›´æ–° package.json ä¸ºä¸‹ä¸€ä¸ªå¼€å‘ç‰ˆæœ¬
          npm version "$NEXT_DEV_VERSION" --no-git-tag-version

          git add package.json
          git commit -m "chore: set next dev version to ${NEXT_DEV_VERSION} after release v${RELEASE_VERSION} [skip ci]"
          git push origin dev

          echo "âœ“ Dev branch updated to $NEXT_DEV_VERSION"

      - name: Create Gitea Release
        uses: https://gitea.com/actions/release-action@main
        with:
          title: "v${{ steps.version.outputs.version }}"
          body: |
            ## å®‰è£…

            ```bash
            npm install -g gitea-mcp-tool@${{ steps.version.outputs.version }}
            ```

            ## æ›´æ–°

            ```bash
            npm update -g gitea-mcp-tool
            ```

            ---
            æŸ¥çœ‹å®Œæ•´æ›´æ–°æ—¥å¿—: [Changelog](https://github.com/SupenBysz/gitea-mcp-tool/wiki/Changelog)
          tag_name: "v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync to GitHub
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "åŒæ­¥ä»£ç å’Œæ ‡ç­¾åˆ° GitHub..."
          git remote add github "https://${{ secrets.GH_SYNC_TOKEN }}@github.com/SupenBysz/gitea-mcp-tool.git" 2>/dev/null || true

          # åŒæ­¥ main åˆ†æ”¯
          git push github main:main --force || echo "::warning::main åˆ†æ”¯åŒæ­¥å¤±è´¥"

          # åŒæ­¥ dev åˆ†æ”¯
          git push github dev:dev --force || echo "::warning::dev åˆ†æ”¯åŒæ­¥å¤±è´¥"

          # åŒæ­¥æ ‡ç­¾
          git push github "v${VERSION}" --force || echo "::warning::æ ‡ç­¾åŒæ­¥å¤±è´¥"

          echo "âœ“ GitHub åŒæ­¥å®Œæˆ"

      - name: Create summary
        run: |
          echo "## æ­£å¼ç‰ˆæœ¬å‘å¸ƒæˆåŠŸ ðŸŽ‰" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**ç‰ˆæœ¬å·**: \`v${{ steps.version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**ä¸‹ä¸€ä¸ªå¼€å‘ç‰ˆæœ¬**: \`${{ steps.version.outputs.next_dev_version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**å®‰è£…å‘½ä»¤**:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "npm install -g gitea-mcp-tool@latest" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**npm**: https://www.npmjs.com/package/gitea-mcp-tool" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**GitHub**: https://github.com/SupenBysz/gitea-mcp-tool" >> $GITHUB_STEP_SUMMARY
