name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Determine version bump type
        id: bump_type
        run: |
          # èŽ·å–æœ€è¿‘çš„ commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # æ ¹æ® commit message å‰ç¼€ç¡®å®šç‰ˆæœ¬ç±»åž‹
          if [[ "$COMMIT_MSG" == *"breaking"* ]] || [[ "$COMMIT_MSG" == *"BREAKING"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == feat:* ]] || [[ "$COMMIT_MSG" == feat\(* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Get npm latest version
        id: npm_latest
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          NPM_LATEST=$(npm view "$PACKAGE_NAME" version --registry https://registry.npmjs.org 2>/dev/null || true)
          echo "npm latest version: ${NPM_LATEST:-none}"
          echo "npm_latest=$NPM_LATEST" >> $GITHUB_OUTPUT

      - name: Bump version
        id: version
        run: |
          # èŽ·å–å½“å‰ç‰ˆæœ¬
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # ç§»é™¤ beta åŽç¼€ï¼ˆå¦‚æžœæœ‰ï¼‰
          BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-beta.*//')

          # è§£æžç‰ˆæœ¬å·
          MAJOR=$(echo "$BASE_VERSION" | cut -d. -f1)
          MINOR=$(echo "$BASE_VERSION" | cut -d. -f2)
          PATCH=$(echo "$BASE_VERSION" | cut -d. -f3)

          # ä¸Ž npm æœ€æ–°æ­£å¼ç‰ˆå¯¹é½ï¼Œé¿å…ç‰ˆæœ¬å†²çª
          NPM_LATEST="${{ steps.npm_latest.outputs.npm_latest }}"
          if [ -n "$NPM_LATEST" ]; then
            COMPARE_BASE=$(printf "%s\n%s\n" "$BASE_VERSION" "$NPM_LATEST" | sort -V | tail -1)
            echo "Compare base vs npm latest: base=$BASE_VERSION, npm=$NPM_LATEST, chosen=$COMPARE_BASE"
            BASE_VERSION="$COMPARE_BASE"
            MAJOR=$(echo "$BASE_VERSION" | cut -d. -f1)
            MINOR=$(echo "$BASE_VERSION" | cut -d. -f2)
            PATCH=$(echo "$BASE_VERSION" | cut -d. -f3)
          fi

          # æ ¹æ®ç±»åž‹é€’å¢žç‰ˆæœ¬
          BUMP_TYPE="${{ steps.bump_type.outputs.type }}"
          case "$BUMP_TYPE" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              # å¦‚æžœå½“å‰æ˜¯ beta ç‰ˆæœ¬ï¼Œç›´æŽ¥ä½¿ç”¨ base version
              if [[ "$CURRENT_VERSION" == *"-beta."* ]]; then
                : # ä¿æŒ PATCH ä¸å˜
              else
                PATCH=$((PATCH + 1))
              fi
              ;;
          esac

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION (bump type: $BUMP_TYPE)"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # æ›´æ–° package.json
          npm version "$NEW_VERSION" --no-git-tag-version

      - name: Update README version
        run: |
          NEW_VERSION="${{ steps.version.outputs.version }}"
          sed -i "s/\*\*å½“å‰ç‰ˆæœ¬\*\*: v[0-9.]*/**å½“å‰ç‰ˆæœ¬**: v${NEW_VERSION}/" README.md || true

      - name: Publish to npm
        run: npm publish --tag latest --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and tag
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          git add package.json README.md
          git commit -m "chore: release v${VERSION} [skip ci]" || true
          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin main --tags || true

      - name: Create Gitea Release
        uses: https://gitea.com/actions/release-action@main
        with:
          title: "v${{ steps.version.outputs.version }}"
          body: |
            ## å®‰è£…

            ```bash
            npm install -g gitea-mcp-tool@${{ steps.version.outputs.version }}
            ```

            ## æ›´æ–°

            ```bash
            npm update -g gitea-mcp-tool
            ```

            ---
            æŸ¥çœ‹å®Œæ•´æ›´æ–°æ—¥å¿—: [Changelog](https://gitea.ktyun.cc/Kysion/entai-gitea-mcp/wiki/Changelog)
          tag_name: "v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          echo "## æ­£å¼ç‰ˆæœ¬å‘å¸ƒæˆåŠŸ ðŸŽ‰" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**ç‰ˆæœ¬å·**: \`v${{ steps.version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**å®‰è£…å‘½ä»¤**:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "npm install -g gitea-mcp-tool@latest" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**npm**: https://www.npmjs.com/package/gitea-mcp-tool" >> $GITHUB_STEP_SUMMARY
